<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon><OutputType>WinExe</OutputType><TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>
    <AssemblyName>Zpevnik</AssemblyName><Version>3.1.30</Version>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier><SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile><IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup><PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4258.31" /></ItemGroup>
  <ItemGroup><EmbeddedResource Include="app.ico" LogicalName="app.ico" /><EmbeddedResource Include="web.zip" LogicalName="web.zip" /><EmbeddedResource Include="PerformanceSmokeTests.js" LogicalName="performance-tests.js" /><EmbeddedResource Include="ModuleSmokeTests.js" LogicalName="module-tests.js" /></ItemGroup>
  <Target Name="RemoveUnusedWpfReference" BeforeTargets="ResolveAssemblyReferences">
    <ItemGroup><Reference Remove="@(Reference)" Condition="'%(Reference.Filename)' == 'Microsoft.Web.WebView2.Wpf'" /></ItemGroup>
  </Target>
</Project>
