export const editorState = {
    detectedChords: new Set(),
    manualChords: new Set(),
    currentDb: [],
    currentArtists: [],
    currentAlbums: [],
    songsDirHandle: null,
    fileHandleMap: new Map(),
    currentSongHandle: null,
    currentSongPath: '',
    coversDirHandle: null,
    coverPreviewToken: 0,
    currentCoverObjectUrl: null,
    currentSongData: null,
    indexerDirHandle: null,
    indexerOutputDirHandle: null,
    currentReviewStatus: {
        state: 'needs_review',
        level: 'orange',
        label: 'Lehká úprava',
        checked: false,
        checked_at: null,
        issues: [],
        note: '',
    },
    currentPlayback: { played: false, played_at: null },
    chordBuilderAccidental: '',
    chordBuilderQuality: '',
    chordBuilderSubtype: '',
    chordBuilderExtension: '',
};
